import os
from datetime import date

from django.core.management.base import BaseCommand
from django.db import transaction

from store.models import Category, Product


CATEGORY_NAMES = {
    'smartphones': 'Smartphones',
    'laptops': 'Laptops',
    'audio': 'Audio',
    'wearables': 'Wearables',
}


PRODUCTS = [
    {
        'slug': 'apple-iphone-15-pro-256',
        'name': 'iPhone 15 Pro 256GB',
        'brand': 'Apple',
        'category': 'smartphones',
        'short_description': 'Compact flagship with premium camera system and smooth 120Hz display.',
        'description': 'iPhone 15 Pro is a high-end phone for users who want top performance, strong cameras, and premium build quality in a compact size.',
        'specs': {
            'Display': '6.1-inch OLED 120Hz',
            'Chipset': 'Apple A17 Pro',
            'RAM': '8GB',
            'Storage': '256GB',
            'Rear Camera': '48MP + 12MP + 12MP',
            'Front Camera': '12MP',
            'Battery': '3274mAh',
            'Charging': 'USB-C 27W + MagSafe 15W',
            'OS': 'iOS 17',
            'Protection': 'IP68',
        },
        'price': '1099.00',
        'compare_at_price': '1199.00',
        'rating': '4.80',
        'review_count': 2450,
        'stock': 38,
        'badge': 'PREMIUM',
        'is_featured': True,
        'released_at': date(2023, 9, 22),
    },
    {
        'slug': 'samsung-galaxy-s24-256',
        'name': 'Galaxy S24 256GB',
        'brand': 'Samsung',
        'category': 'smartphones',
        'short_description': 'Fast Android flagship with bright display and strong AI tools.',
        'description': 'Galaxy S24 is a balanced flagship with premium display quality, reliable cameras, and all-day battery life.',
        'specs': {
            'Display': '6.2-inch Dynamic AMOLED 120Hz',
            'Chipset': 'Snapdragon 8 Gen 3',
            'RAM': '8GB',
            'Storage': '256GB',
            'Rear Camera': '50MP + 12MP + 10MP',
            'Front Camera': '12MP',
            'Battery': '4000mAh',
            'Charging': '25W wired + 15W wireless',
            'OS': 'Android 14',
            'Protection': 'IP68',
        },
        'price': '899.00',
        'compare_at_price': '999.00',
        'rating': '4.70',
        'review_count': 1890,
        'stock': 52,
        'badge': 'NEW',
        'is_featured': True,
        'released_at': date(2024, 1, 31),
    },
    {
        'slug': 'google-pixel-8-pro-128',
        'name': 'Pixel 8 Pro 128GB',
        'brand': 'Google',
        'category': 'smartphones',
        'short_description': 'Camera-focused Android phone with clean software and smart AI features.',
        'description': 'Pixel 8 Pro is ideal for photo lovers and users who prefer a clean Android experience with long software support.',
        'specs': {
            'Display': '6.7-inch LTPO OLED 120Hz',
            'Chipset': 'Google Tensor G3',
            'RAM': '12GB',
            'Storage': '128GB',
            'Rear Camera': '50MP + 48MP + 48MP',
            'Front Camera': '10.5MP',
            'Battery': '5050mAh',
            'Charging': '30W wired + 23W wireless',
            'OS': 'Android 14',
            'Protection': 'IP68',
        },
        'price': '999.00',
        'compare_at_price': '1099.00',
        'rating': '4.70',
        'review_count': 1310,
        'stock': 29,
        'badge': 'CAMERA PICK',
        'is_featured': True,
        'released_at': date(2023, 10, 12),
    },
    {
        'slug': 'oneplus-12-256',
        'name': 'OnePlus 12 256GB',
        'brand': 'OnePlus',
        'category': 'smartphones',
        'short_description': 'High-performance flagship with fast charging and smooth display.',
        'description': 'OnePlus 12 delivers flagship speed and long battery life with one of the fastest charging systems in this class.',
        'specs': {
            'Display': '6.82-inch AMOLED 120Hz',
            'Chipset': 'Snapdragon 8 Gen 3',
            'RAM': '12GB',
            'Storage': '256GB',
            'Rear Camera': '50MP + 64MP + 48MP',
            'Front Camera': '32MP',
            'Battery': '5400mAh',
            'Charging': '100W wired + 50W wireless',
            'OS': 'Android 14',
            'Protection': 'IP65',
        },
        'price': '799.00',
        'compare_at_price': '899.00',
        'rating': '4.60',
        'review_count': 980,
        'stock': 44,
        'badge': 'FAST CHARGE',
        'is_featured': False,
        'released_at': date(2024, 1, 23),
    },
    {
        'slug': 'xiaomi-14-512',
        'name': 'Xiaomi 14 512GB',
        'brand': 'Xiaomi',
        'category': 'smartphones',
        'short_description': 'Compact flagship with Leica-tuned cameras and strong battery life.',
        'description': 'Xiaomi 14 is a premium compact phone with strong imaging and top-tier performance in a smaller body.',
        'specs': {
            'Display': '6.36-inch AMOLED 120Hz',
            'Chipset': 'Snapdragon 8 Gen 3',
            'RAM': '12GB',
            'Storage': '512GB',
            'Rear Camera': '50MP + 50MP + 50MP',
            'Front Camera': '32MP',
            'Battery': '4610mAh',
            'Charging': '90W wired + 50W wireless',
            'OS': 'Android 14',
            'Protection': 'IP68',
        },
        'price': '849.00',
        'compare_at_price': '949.00',
        'rating': '4.60',
        'review_count': 760,
        'stock': 34,
        'badge': 'COMPACT FLAGSHIP',
        'is_featured': False,
        'released_at': date(2024, 2, 26),
    },
    {
        'slug': 'apple-macbook-air-13-m3-16-512',
        'name': 'MacBook Air 13 M3 16GB 512GB',
        'brand': 'Apple',
        'category': 'laptops',
        'short_description': 'Lightweight premium laptop with long battery life and silent operation.',
        'description': 'MacBook Air M3 is great for everyday productivity, coding, and creative tasks with excellent battery efficiency.',
        'specs': {
            'Display': '13.6-inch Liquid Retina',
            'CPU': 'Apple M3 8-core',
            'GPU': '10-core integrated',
            'RAM': '16GB unified',
            'Storage': '512GB SSD',
            'Battery': 'Up to 18 hours',
            'Weight': '1.24kg',
            'Ports': 'MagSafe + 2x Thunderbolt/USB4',
            'Wireless': 'Wi-Fi 6E + BT 5.3',
            'OS': 'macOS',
        },
        'price': '1499.00',
        'compare_at_price': '1599.00',
        'rating': '4.80',
        'review_count': 1420,
        'stock': 24,
        'badge': 'BESTSELLER',
        'is_featured': True,
        'released_at': date(2024, 3, 8),
    },
    {
        'slug': 'dell-xps-14-9440',
        'name': 'Dell XPS 14 9440',
        'brand': 'Dell',
        'category': 'laptops',
        'short_description': 'Premium Windows laptop with OLED screen and strong creator performance.',
        'description': 'XPS 14 is designed for users who need a portable but powerful machine for work, editing, and multitasking.',
        'specs': {
            'Display': '14.5-inch 3.2K OLED 120Hz',
            'CPU': 'Intel Core Ultra 7 155H',
            'GPU': 'NVIDIA RTX 4050',
            'RAM': '32GB LPDDR5x',
            'Storage': '1TB SSD',
            'Battery': '69.5Wh',
            'Weight': '1.68kg',
            'Ports': '2x Thunderbolt 4 + USB-C adapter',
            'Wireless': 'Wi-Fi 7 + BT 5.4',
            'OS': 'Windows 11',
        },
        'price': '1999.00',
        'compare_at_price': '2199.00',
        'rating': '4.60',
        'review_count': 690,
        'stock': 17,
        'badge': 'CREATOR',
        'is_featured': False,
        'released_at': date(2024, 2, 20),
    },
    {
        'slug': 'lenovo-thinkpad-x1-carbon-gen12',
        'name': 'ThinkPad X1 Carbon Gen 12',
        'brand': 'Lenovo',
        'category': 'laptops',
        'short_description': 'Business ultrabook with excellent keyboard and strong portability.',
        'description': 'ThinkPad X1 Carbon is a durable business laptop focused on reliability, security, and typing comfort.',
        'specs': {
            'Display': '14-inch 2.8K OLED',
            'CPU': 'Intel Core Ultra 7 155U',
            'GPU': 'Intel integrated',
            'RAM': '16GB LPDDR5x',
            'Storage': '1TB SSD',
            'Battery': '57Wh',
            'Weight': '1.12kg',
            'Ports': '2x Thunderbolt 4 + 2x USB-A + HDMI',
            'Wireless': 'Wi-Fi 6E + BT 5.3',
            'OS': 'Windows 11 Pro',
        },
        'price': '1799.00',
        'compare_at_price': '1949.00',
        'rating': '4.70',
        'review_count': 540,
        'stock': 21,
        'badge': 'BUSINESS',
        'is_featured': False,
        'released_at': date(2024, 1, 15),
    },
    {
        'slug': 'asus-rog-zephyrus-g14-2024',
        'name': 'ROG Zephyrus G14 2024',
        'brand': 'ASUS',
        'category': 'laptops',
        'short_description': 'Compact gaming laptop with high refresh OLED display.',
        'description': 'Zephyrus G14 combines gaming power and portability, suitable for both creators and gamers.',
        'specs': {
            'Display': '14-inch 3K OLED 120Hz',
            'CPU': 'AMD Ryzen 9 8945HS',
            'GPU': 'NVIDIA RTX 4060',
            'RAM': '32GB LPDDR5x',
            'Storage': '1TB SSD',
            'Battery': '73Wh',
            'Weight': '1.5kg',
            'Ports': 'USB4 + USB-C + USB-A + HDMI',
            'Wireless': 'Wi-Fi 6E + BT 5.3',
            'OS': 'Windows 11',
        },
        'price': '1899.00',
        'compare_at_price': '2049.00',
        'rating': '4.70',
        'review_count': 510,
        'stock': 14,
        'badge': 'GAMING',
        'is_featured': True,
        'released_at': date(2024, 3, 10),
    },
    {
        'slug': 'hp-spectre-x360-14',
        'name': 'HP Spectre x360 14',
        'brand': 'HP',
        'category': 'laptops',
        'short_description': 'Convertible 2-in-1 laptop for productivity and media.',
        'description': 'Spectre x360 14 is a premium touchscreen laptop with flexible tablet mode and solid battery life.',
        'specs': {
            'Display': '14-inch 2.8K OLED touch',
            'CPU': 'Intel Core Ultra 7 155H',
            'GPU': 'Intel Arc integrated',
            'RAM': '16GB LPDDR5x',
            'Storage': '1TB SSD',
            'Battery': '68Wh',
            'Weight': '1.44kg',
            'Ports': '2x Thunderbolt 4 + USB-A',
            'Wireless': 'Wi-Fi 7 + BT 5.4',
            'OS': 'Windows 11',
        },
        'price': '1649.00',
        'compare_at_price': '1799.00',
        'rating': '4.60',
        'review_count': 460,
        'stock': 19,
        'badge': '2-IN-1',
        'is_featured': False,
        'released_at': date(2024, 2, 5),
    },
    {
        'slug': 'sony-wh-1000xm5',
        'name': 'WH-1000XM5',
        'brand': 'Sony',
        'category': 'audio',
        'short_description': 'Premium wireless over-ear headphones with top-class noise canceling.',
        'description': 'WH-1000XM5 offers excellent ANC, clear sound, and comfort for long daily listening sessions.',
        'specs': {
            'Type': 'Over-ear wireless',
            'Drivers': '30mm dynamic',
            'ANC': 'Adaptive ANC',
            'Battery': 'Up to 30h with ANC',
            'Charging': 'USB-C fast charge',
            'Bluetooth': '5.2',
            'Codecs': 'SBC AAC LDAC',
            'Microphones': '8 mics',
            'Weight': '250g',
            'Multipoint': 'Yes',
        },
        'price': '349.00',
        'compare_at_price': '399.00',
        'rating': '4.80',
        'review_count': 2750,
        'stock': 66,
        'badge': 'TOP RATED',
        'is_featured': True,
        'released_at': date(2022, 5, 20),
    },
    {
        'slug': 'bose-quietcomfort-ultra-headphones',
        'name': 'QuietComfort Ultra Headphones',
        'brand': 'Bose',
        'category': 'audio',
        'short_description': 'Comfortable ANC headphones with immersive spatial audio mode.',
        'description': 'QuietComfort Ultra focuses on comfort, premium noise cancellation, and warm sound signature.',
        'specs': {
            'Type': 'Over-ear wireless',
            'Drivers': 'Dynamic drivers',
            'ANC': 'CustomTune ANC',
            'Battery': 'Up to 24h',
            'Charging': 'USB-C',
            'Bluetooth': '5.3',
            'Codecs': 'SBC AAC aptX Adaptive',
            'Microphones': 'Beamforming array',
            'Weight': '254g',
            'Multipoint': 'Yes',
        },
        'price': '429.00',
        'compare_at_price': '479.00',
        'rating': '4.70',
        'review_count': 1180,
        'stock': 41,
        'badge': 'PREMIUM',
        'is_featured': False,
        'released_at': date(2023, 10, 3),
    },
    {
        'slug': 'apple-airpods-pro-2-usbc',
        'name': 'AirPods Pro 2 USB-C',
        'brand': 'Apple',
        'category': 'audio',
        'short_description': 'Premium true wireless earbuds with adaptive ANC and seamless Apple pairing.',
        'description': 'AirPods Pro 2 are compact, easy to use, and ideal for Apple ecosystem users.',
        'specs': {
            'Type': 'True wireless earbuds',
            'Drivers': 'Custom high-excursion driver',
            'ANC': 'Adaptive ANC + Transparency',
            'Battery': 'Up to 6h earbuds / 30h with case',
            'Charging': 'USB-C + MagSafe',
            'Bluetooth': '5.3',
            'Codecs': 'AAC',
            'Water Resistance': 'IP54 (earbuds and case)',
            'Spatial Audio': 'Personalized',
            'Controls': 'Touch stems',
        },
        'price': '249.00',
        'compare_at_price': '279.00',
        'rating': '4.80',
        'review_count': 3320,
        'stock': 74,
        'badge': 'POPULAR',
        'is_featured': True,
        'released_at': date(2023, 9, 22),
    },
    {
        'slug': 'sennheiser-momentum-4-wireless',
        'name': 'Momentum 4 Wireless',
        'brand': 'Sennheiser',
        'category': 'audio',
        'short_description': 'Long-battery over-ear headphones with rich detailed sound.',
        'description': 'Momentum 4 is designed for listeners who want long battery life and high audio quality.',
        'specs': {
            'Type': 'Over-ear wireless',
            'Drivers': '42mm dynamic',
            'ANC': 'Hybrid ANC',
            'Battery': 'Up to 60h',
            'Charging': 'USB-C fast charge',
            'Bluetooth': '5.2',
            'Codecs': 'SBC AAC aptX aptX Adaptive',
            'Microphones': '4 mics',
            'Weight': '293g',
            'Multipoint': 'Yes',
        },
        'price': '379.00',
        'compare_at_price': '429.00',
        'rating': '4.70',
        'review_count': 940,
        'stock': 33,
        'badge': 'LONG BATTERY',
        'is_featured': False,
        'released_at': date(2022, 8, 23),
    },
    {
        'slug': 'jbl-live-770nc',
        'name': 'Live 770NC',
        'brand': 'JBL',
        'category': 'audio',
        'short_description': 'Value-focused wireless ANC headphones with energetic sound.',
        'description': 'Live 770NC provides strong everyday performance with long battery and practical features.',
        'specs': {
            'Type': 'Over-ear wireless',
            'Drivers': '40mm dynamic',
            'ANC': 'True Adaptive ANC',
            'Battery': 'Up to 50h ANC off / 40h ANC on',
            'Charging': 'USB-C',
            'Bluetooth': '5.3',
            'Codecs': 'SBC AAC',
            'Microphones': '4 mics',
            'Weight': '256g',
            'Multipoint': 'Yes',
        },
        'price': '199.00',
        'compare_at_price': '229.00',
        'rating': '4.50',
        'review_count': 680,
        'stock': 57,
        'badge': 'VALUE PICK',
        'is_featured': False,
        'released_at': date(2023, 9, 1),
    },
    {
        'slug': 'apple-watch-series-9-45mm-gps',
        'name': 'Watch Series 9 45mm GPS',
        'brand': 'Apple',
        'category': 'wearables',
        'short_description': 'Smartwatch with bright display and smooth fitness plus notification experience.',
        'description': 'Apple Watch Series 9 is a balanced smartwatch for health tracking, workouts, and daily convenience.',
        'specs': {
            'Display': '1.9-inch Retina LTPO OLED',
            'Case': 'Aluminum 45mm',
            'Chip': 'S9 SiP',
            'Sensors': 'Heart rate ECG blood oxygen temp',
            'GPS': 'Yes',
            'Connectivity': 'Bluetooth 5.3 Wi-Fi NFC',
            'Battery': 'Up to 18h',
            'Water Resistance': '50m',
            'OS': 'watchOS',
            'Compatibility': 'iPhone',
        },
        'price': '429.00',
        'compare_at_price': '479.00',
        'rating': '4.70',
        'review_count': 2240,
        'stock': 46,
        'badge': 'BESTSELLER',
        'is_featured': True,
        'released_at': date(2023, 9, 22),
    },
    {
        'slug': 'samsung-galaxy-watch6-classic-47mm',
        'name': 'Galaxy Watch6 Classic 47mm',
        'brand': 'Samsung',
        'category': 'wearables',
        'short_description': 'Premium smartwatch with rotating bezel and strong health tracking.',
        'description': 'Galaxy Watch6 Classic combines traditional watch feel with modern smartwatch fitness features.',
        'specs': {
            'Display': '1.5-inch Super AMOLED',
            'Case': 'Stainless steel 47mm',
            'Chip': 'Exynos W930',
            'Sensors': 'Heart rate ECG BIA temp',
            'GPS': 'Dual-band',
            'Connectivity': 'Bluetooth 5.3 Wi-Fi NFC',
            'Battery': '425mAh',
            'Water Resistance': '5ATM + IP68',
            'OS': 'Wear OS',
            'Compatibility': 'Android',
        },
        'price': '399.00',
        'compare_at_price': '449.00',
        'rating': '4.60',
        'review_count': 1290,
        'stock': 39,
        'badge': 'CLASSIC',
        'is_featured': False,
        'released_at': date(2023, 8, 11),
    },
    {
        'slug': 'google-pixel-watch-2',
        'name': 'Pixel Watch 2',
        'brand': 'Google',
        'category': 'wearables',
        'short_description': 'Lightweight smartwatch with Fitbit-powered health tracking.',
        'description': 'Pixel Watch 2 offers clean design and practical health insights integrated with Google services.',
        'specs': {
            'Display': '1.2-inch AMOLED',
            'Case': 'Aluminum 41mm',
            'Chip': 'Qualcomm SW5100',
            'Sensors': 'Heart rate ECG skin temp SpO2',
            'GPS': 'Yes',
            'Connectivity': 'Bluetooth 5.0 Wi-Fi NFC',
            'Battery': 'Up to 24h',
            'Water Resistance': '5ATM',
            'OS': 'Wear OS',
            'Compatibility': 'Android',
        },
        'price': '349.00',
        'compare_at_price': '399.00',
        'rating': '4.50',
        'review_count': 710,
        'stock': 31,
        'badge': 'LIGHTWEIGHT',
        'is_featured': False,
        'released_at': date(2023, 10, 12),
    },
    {
        'slug': 'garmin-venu-3',
        'name': 'Venu 3',
        'brand': 'Garmin',
        'category': 'wearables',
        'short_description': 'Fitness-focused smartwatch with very strong battery life and recovery metrics.',
        'description': 'Venu 3 is made for active users who prioritize training insights and health metrics.',
        'specs': {
            'Display': '1.4-inch AMOLED',
            'Case': '45mm fiber-reinforced polymer',
            'Sensors': 'Heart rate pulse ox stress HRV',
            'GPS': 'Multi-GNSS',
            'Connectivity': 'Bluetooth Wi-Fi ANT+',
            'Battery': 'Up to 14 days smartwatch mode',
            'Water Resistance': '5ATM',
            'OS': 'Garmin OS',
            'Compatibility': 'Android and iOS',
        },
        'price': '449.00',
        'compare_at_price': '499.00',
        'rating': '4.60',
        'review_count': 520,
        'stock': 22,
        'badge': 'FITNESS PRO',
        'is_featured': False,
        'released_at': date(2023, 8, 30),
    },
    {
        'slug': 'huawei-watch-gt-4-46mm',
        'name': 'Watch GT 4 46mm',
        'brand': 'Huawei',
        'category': 'wearables',
        'short_description': 'Stylish smartwatch with long battery life and broad workout support.',
        'description': 'Watch GT 4 is a practical daily smartwatch focused on battery life, health tracking, and comfort.',
        'specs': {
            'Display': '1.43-inch AMOLED',
            'Case': '46mm stainless steel',
            'Sensors': 'Heart rate SpO2 stress sleep',
            'GPS': 'Dual-band GNSS',
            'Connectivity': 'Bluetooth 5.2',
            'Battery': 'Up to 14 days',
            'Water Resistance': '5ATM',
            'OS': 'HarmonyOS',
            'Compatibility': 'Android and iOS',
            'Workout Modes': '100+',
        },
        'price': '279.00',
        'compare_at_price': '329.00',
        'rating': '4.50',
        'review_count': 480,
        'stock': 35,
        'badge': 'LONG BATTERY',
        'is_featured': False,
        'released_at': date(2023, 10, 4),
    },
]


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def random_image_url(slug: str, suffix: str) -> str:
    return f'https://picsum.photos/seed/{slug}-{suffix}/1200/900'


def build_product_defaults(payload: dict) -> dict:
    slug = payload['slug']
    return {
        'name': payload['name'],
        'brand': payload['brand'],
        'category': payload['category'],
        'short_description': payload['short_description'],
        'description': payload['description'],
        'specs': payload['specs'],
        'price': payload['price'],
        'compare_at_price': payload['compare_at_price'],
        'rating': payload['rating'],
        'review_count': payload['review_count'],
        'stock': payload['stock'],
        'image_url': random_image_url(slug, 'main'),
        'gallery': [
            random_image_url(slug, 'gallery-1'),
            random_image_url(slug, 'gallery-2'),
            random_image_url(slug, 'gallery-3'),
        ],
        'badge': payload['badge'],
        'is_active': True,
        'is_featured': payload['is_featured'],
        'released_at': payload['released_at'],
    }


class Command(BaseCommand):
    help = 'Seed category and product data for storefront catalog. Safe to run on every deploy.'

    def handle(self, *args, **options):
        update_existing = env_bool('ELECTRA_SEED_UPDATE_EXISTING', default=True)
        replace_images = env_bool('ELECTRA_SEED_REPLACE_IMAGES', default=False)

        self.ensure_categories()

        created_count = 0
        updated_count = 0
        skipped_count = 0

        with transaction.atomic():
            for payload in PRODUCTS:
                slug = payload['slug']
                defaults = build_product_defaults(payload)

                product, created = Product.objects.get_or_create(slug=slug, defaults=defaults)
                if created:
                    created_count += 1
                    continue

                changed = False

                if update_existing:
                    for field, value in defaults.items():
                        if field in {'image_url', 'gallery'}:
                            continue
                        setattr(product, field, value)
                    changed = True

                if replace_images or not product.image_url:
                    product.image_url = defaults['image_url']
                    product.gallery = defaults['gallery']
                    changed = True

                if changed:
                    product.save()
                    updated_count += 1
                else:
                    skipped_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                (
                    'Seed complete. '
                    f'Created: {created_count}, Updated: {updated_count}, Skipped: {skipped_count}, '
                    f'Total Products: {Product.objects.count()}, Total Categories: {Category.objects.count()}.'
                )
            )
        )

    def ensure_categories(self):
        for slug, name in CATEGORY_NAMES.items():
            Category.objects.get_or_create(slug=slug, defaults={'name': name})
