# Generated by Django 6.0.4 on 2026-04-12 17:51

from django.db import migrations, models
from django.utils.text import slugify


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    defaults = [
        ('smartphones', 'Smartphones'),
        ('laptops', 'Laptops'),
        ('audio', 'Audio'),
        ('wearables', 'Wearables'),
        ('tablets', 'Tablets'),
        ('monitors', 'Monitors'),
    ]

    for slug, name in defaults:
        Category.objects.get_or_create(slug=slug, defaults={'name': name})

    existing_slugs = Product.objects.values_list('category', flat=True).distinct()
    for raw_slug in existing_slugs:
        slug = (raw_slug or '').strip().lower()
        if not slug:
            continue

        if Category.objects.filter(slug=slug).exists():
            continue

        fallback_slug = slugify(slug) or f'category-{Category.objects.count() + 1}'
        if fallback_slug != slug and Category.objects.filter(slug=fallback_slug).exists():
            fallback_slug = f'{fallback_slug}-{Category.objects.count() + 1}'

        base_name = slug.replace('-', ' ').replace('_', ' ').title() or 'Category'
        name = base_name
        counter = 2
        while Category.objects.filter(name=name).exists():
            name = f'{base_name} {counter}'
            counter += 1

        Category.objects.create(slug=fallback_slug if fallback_slug else slug, name=name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.RunPython(create_initial_categories, noop_reverse),
    ]
